# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created: Sat Mar 29 21:39:05 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(465, 374)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Preferences.sizePolicy().hasHeightForWidth())
        Preferences.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Preferences)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Preferences)
        self.tabWidget.setObjectName("tabWidget")
        self.settings = QtGui.QWidget()
        self.settings.setObjectName("settings")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.settings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget_2 = QtGui.QTabWidget(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_honeycomb = QtGui.QWidget()
        self.tab_honeycomb.setObjectName("tab_honeycomb")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_honeycomb)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.dimensionsLabel1 = QtGui.QLabel(self.tab_honeycomb)
        self.dimensionsLabel1.setObjectName("dimensionsLabel1")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.dimensionsLabel1)
        self.honeycombGLayout = QtGui.QGridLayout()
        self.honeycombGLayout.setContentsMargins(-1, 3, -1, -1)
        self.honeycombGLayout.setObjectName("honeycombGLayout")
        self.honeycombRowsSpinBox = QtGui.QSpinBox(self.tab_honeycomb)
        self.honeycombRowsSpinBox.setMinimum(6)
        self.honeycombRowsSpinBox.setMaximum(200)
        self.honeycombRowsSpinBox.setProperty("value", 30)
        self.honeycombRowsSpinBox.setObjectName("honeycombRowsSpinBox")
        self.honeycombGLayout.addWidget(self.honeycombRowsSpinBox, 0, 0, 1, 1)
        self.honeycombColsSpinBox = QtGui.QSpinBox(self.tab_honeycomb)
        self.honeycombColsSpinBox.setMinimum(6)
        self.honeycombColsSpinBox.setMaximum(200)
        self.honeycombColsSpinBox.setProperty("value", 32)
        self.honeycombColsSpinBox.setObjectName("honeycombColsSpinBox")
        self.honeycombGLayout.addWidget(self.honeycombColsSpinBox, 0, 1, 1, 1)
        self.hRowsLabel = QtGui.QLabel(self.tab_honeycomb)
        self.hRowsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hRowsLabel.setObjectName("hRowsLabel")
        self.honeycombGLayout.addWidget(self.hRowsLabel, 1, 0, 1, 1)
        self.hColsLabel = QtGui.QLabel(self.tab_honeycomb)
        self.hColsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hColsLabel.setObjectName("hColsLabel")
        self.honeycombGLayout.addWidget(self.hColsLabel, 1, 1, 1, 1)
        self.honeycombStepsSpinBox = QtGui.QSpinBox(self.tab_honeycomb)
        self.honeycombStepsSpinBox.setMinimum(2)
        self.honeycombStepsSpinBox.setMaximum(2000)
        self.honeycombStepsSpinBox.setSingleStep(1)
        self.honeycombStepsSpinBox.setProperty("value", 2)
        self.honeycombStepsSpinBox.setObjectName("honeycombStepsSpinBox")
        self.honeycombGLayout.addWidget(self.honeycombStepsSpinBox, 0, 2, 1, 1)
        self.hBasesLabel = QtGui.QLabel(self.tab_honeycomb)
        self.hBasesLabel.setObjectName("hBasesLabel")
        self.honeycombGLayout.addWidget(self.hBasesLabel, 1, 2, 1, 1)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.FieldRole, self.honeycombGLayout)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/part/dlg_honeycomb"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_honeycomb, icon, "")
        self.tab_square = QtGui.QWidget()
        self.tab_square.setObjectName("tab_square")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_square)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dimensionsLabel2 = QtGui.QLabel(self.tab_square)
        self.dimensionsLabel2.setObjectName("dimensionsLabel2")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.dimensionsLabel2)
        self.squareGLayout = QtGui.QGridLayout()
        self.squareGLayout.setContentsMargins(-1, 3, -1, -1)
        self.squareGLayout.setObjectName("squareGLayout")
        self.squareRowsSpinBox = QtGui.QSpinBox(self.tab_square)
        self.squareRowsSpinBox.setMinimum(6)
        self.squareRowsSpinBox.setMaximum(200)
        self.squareRowsSpinBox.setProperty("value", 30)
        self.squareRowsSpinBox.setObjectName("squareRowsSpinBox")
        self.squareGLayout.addWidget(self.squareRowsSpinBox, 0, 0, 1, 1)
        self.squareColsSpinBox = QtGui.QSpinBox(self.tab_square)
        self.squareColsSpinBox.setMinimum(6)
        self.squareColsSpinBox.setMaximum(200)
        self.squareColsSpinBox.setProperty("value", 30)
        self.squareColsSpinBox.setObjectName("squareColsSpinBox")
        self.squareGLayout.addWidget(self.squareColsSpinBox, 0, 1, 1, 1)
        self.sRowsLabel = QtGui.QLabel(self.tab_square)
        self.sRowsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sRowsLabel.setObjectName("sRowsLabel")
        self.squareGLayout.addWidget(self.sRowsLabel, 1, 0, 1, 1)
        self.sColsLabel = QtGui.QLabel(self.tab_square)
        self.sColsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sColsLabel.setObjectName("sColsLabel")
        self.squareGLayout.addWidget(self.sColsLabel, 1, 1, 1, 1)
        self.squareStepsSpinBox = QtGui.QSpinBox(self.tab_square)
        self.squareStepsSpinBox.setMinimum(2)
        self.squareStepsSpinBox.setMaximum(2000)
        self.squareStepsSpinBox.setObjectName("squareStepsSpinBox")
        self.squareGLayout.addWidget(self.squareStepsSpinBox, 0, 2, 1, 1)
        self.sBasesLabel = QtGui.QLabel(self.tab_square)
        self.sBasesLabel.setObjectName("sBasesLabel")
        self.squareGLayout.addWidget(self.sBasesLabel, 1, 2, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.squareGLayout)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/part/dlg_square"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_square, icon1, "")
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.autoscafLabel = QtGui.QLabel(self.settings)
        self.autoscafLabel.setObjectName("autoscafLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.autoscafLabel)
        self.autoScafComboBox = QtGui.QComboBox(self.settings)
        self.autoScafComboBox.setObjectName("autoScafComboBox")
        self.autoScafComboBox.addItem("")
        self.autoScafComboBox.addItem("")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.autoScafComboBox)
        self.zoomSpeedLabel = QtGui.QLabel(self.settings)
        self.zoomSpeedLabel.setObjectName("zoomSpeedLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.zoomSpeedLabel)
        self.zoomSpeedSlider = QtGui.QSlider(self.settings)
        self.zoomSpeedSlider.setMinimumSize(QtCore.QSize(140, 0))
        self.zoomSpeedSlider.setMinimum(1)
        self.zoomSpeedSlider.setMaximum(100)
        self.zoomSpeedSlider.setSingleStep(1)
        self.zoomSpeedSlider.setProperty("value", 50)
        self.zoomSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSpeedSlider.setInvertedControls(False)
        self.zoomSpeedSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.zoomSpeedSlider.setTickInterval(0)
        self.zoomSpeedSlider.setObjectName("zoomSpeedSlider")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.zoomSpeedSlider)
        self.defaultToolComboBox = QtGui.QComboBox(self.settings)
        self.defaultToolComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.defaultToolComboBox.setObjectName("defaultToolComboBox")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pathtools/dlg_select"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.defaultToolComboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pathtools/dlg_pencil"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.defaultToolComboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pathtools/dlg_paint"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.defaultToolComboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pathtools/dlg_addseq"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.defaultToolComboBox.addItem(icon5, "")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.defaultToolComboBox)
        self.defaultToolLabel = QtGui.QLabel(self.settings)
        self.defaultToolLabel.setObjectName("defaultToolLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.defaultToolLabel)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.buttonBox = QtGui.QDialogButtonBox(self.settings)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.tabWidget.addTab(self.settings, "")
        self.plugins = QtGui.QWidget()
        self.plugins.setObjectName("plugins")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.plugins)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pluginTableWidget = QtGui.QTableWidget(self.plugins)
        self.pluginTableWidget.setObjectName("pluginTableWidget")
        self.pluginTableWidget.setColumnCount(1)
        self.pluginTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.pluginTableWidget.setHorizontalHeaderItem(0, item)
        self.pluginTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.pluginTableWidget)
        self.addPluginButton = QtGui.QPushButton(self.plugins)
        self.addPluginButton.setObjectName("addPluginButton")
        self.verticalLayout_5.addWidget(self.addPluginButton)
        self.tabWidget.addTab(self.plugins, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.actionClose = QtGui.QAction(Preferences)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.defaultToolComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(QtGui.QApplication.translate("Preferences", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.dimensionsLabel1.setText(QtGui.QApplication.translate("Preferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Default</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dimensions</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.hRowsLabel.setText(QtGui.QApplication.translate("Preferences", "rows", None, QtGui.QApplication.UnicodeUTF8))
        self.hColsLabel.setText(QtGui.QApplication.translate("Preferences", "columns", None, QtGui.QApplication.UnicodeUTF8))
        self.hBasesLabel.setText(QtGui.QApplication.translate("Preferences", "bases (x21)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_honeycomb), QtGui.QApplication.translate("Preferences", "Honeycomb", None, QtGui.QApplication.UnicodeUTF8))
        self.dimensionsLabel2.setText(QtGui.QApplication.translate("Preferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Default</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dimensions</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.sRowsLabel.setText(QtGui.QApplication.translate("Preferences", "rows", None, QtGui.QApplication.UnicodeUTF8))
        self.sColsLabel.setText(QtGui.QApplication.translate("Preferences", "columns", None, QtGui.QApplication.UnicodeUTF8))
        self.sBasesLabel.setText(QtGui.QApplication.translate("Preferences", "bases (x32)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_square), QtGui.QApplication.translate("Preferences", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.autoscafLabel.setText(QtGui.QApplication.translate("Preferences", "Auto-scaffold style:", None, QtGui.QApplication.UnicodeUTF8))
        self.autoScafComboBox.setItemText(0, QtGui.QApplication.translate("Preferences", "Mid-seam", None, QtGui.QApplication.UnicodeUTF8))
        self.autoScafComboBox.setItemText(1, QtGui.QApplication.translate("Preferences", "Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomSpeedLabel.setText(QtGui.QApplication.translate("Preferences", "Mousewheel zoom speed:", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultToolComboBox.setItemText(0, QtGui.QApplication.translate("Preferences", "Select Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultToolComboBox.setItemText(1, QtGui.QApplication.translate("Preferences", "Pencil Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultToolComboBox.setItemText(2, QtGui.QApplication.translate("Preferences", "Paint", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultToolComboBox.setItemText(3, QtGui.QApplication.translate("Preferences", "Add Seq", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultToolLabel.setText(QtGui.QApplication.translate("Preferences", "Default tool at startup:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), QtGui.QApplication.translate("Preferences", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Preferences", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.addPluginButton.setText(QtGui.QApplication.translate("Preferences", "Add Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plugins), QtGui.QApplication.translate("Preferences", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("Preferences", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("Preferences", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))

import dialogicons_rc
